### ISSUE TITLE
Can't unmark tiles made with original Ground Markers plugin

### ISSUE THREAD

**Issue by OilyHands** [Stevester118/Ground-Markers-With-Labels#2]
I believe you have to turn off the Ground Markers With Labels plugin in order to unmark tiles made with the original ground markers plugin. See video: https://imgur.com/a/eOjgl08

**Comment by SteveDevGit** [comment]
Both plugins cannot be used with each other. The Ground Markers With Labels plugin is literally the original plugin with label functionality. Not sure why they didn't want to add it to the existing plugin but that's why I added this to the plugin hub.

**Comment by OilyHands** [comment]
Oh, thanks for the clarification. It's a great plugin. Thank you for making
it!

**Comment by SteveDevGit** [comment]
I'm happy you appreciate it. If you have any other suggestions or questions, let me know.
