### ISSUE TITLE
Plugin no longer works

### ISSUE THREAD

**Issue by leftbones** [Stevester118/Ground-Markers-With-Labels#3]
Not sure what changed, but a few days ago I logged in and the plugin no longer works. My marked tiles are gone and I can't create new ones.

**Comment by SteveDevGit** [comment]
Hello @evprkr ,

This plugin is deprecated and no longer needed as the native RuneLite Ground Markers plugin includes this functionality.

**Comment by leftbones** [comment]
Oops, not sure how I didn't realize that.

Thanks!

**Comment by SteveDevGit** [comment]
No worries :)
